### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by willrnch** [0LNetworkCommunity/documentation#62]
Those are the problem I encountered during the validator/VFN setup:

#### Issue

[The documentation](https://0lnetwork.dev/validators/restore#initialize-configs), states to run `libra config fullnode-init`. This command fails with the following error: `Error: unable to parse HashValue`

#### Solution

Solution was found [on discord](https://discord.com/channels/833074824447655976/1166446495004905584/1189102925646147666).

> You can ignore that error and grab the genesis blob and waypoint from the repo direct: https://github.com/0LNetworkCommunity/epoch-archive-mainnet/tree/main/upgrades/v6.9.0

#### Issue

[The documentation](https://0lnetwork.dev/validators/restore#clone-and-build-the-epoch-archive-mainnet-repository), states to run `make bins`. This command fails with the following error: `sudo: command not found`

#### Solution
I do not have sudo because I'm using docker. I edited the Makefile to remove all references to sudo.

#### Issue
Running [`make bins`](https://0lnetwork.dev/validators/restore#clone-and-build-the-epoch-archive-mainnet-repository) fails if `jq` and `bc` are not installed (which is the case in docker)

#### Solution
`apt install -y jq bc`

#### Issue

`make restore-all` fails with:

```
rm -rf ~/.libra/data/db
if [  -eq 0 ]; then \
	make restore-init; \
fi
bash: line 1: [: -eq: unary operator expected
```

#### Solution

```diff
 restore-all: sync-repo wipe-db
-       if [ $(SKIP_INIT) -eq 0 ]; then \
-               make restore-init; \
-       fi
+       # if [ $(SKIP_INIT) -eq 0 ]; then
+       #       make restore-init;
+       # fi
        make restore-genesis
```

#### Issue

```sh
cd ~/epoch-archive-mainnet/snapshots/
diem-db-tool restore bootstrap-db --target-db-dir ~/.libra/data/db --metadata-cache-dir ~/epoch-archive-mainnet/metacache --command-adapter-config ~/epoch-archive-mainnet/epoch-archive.yaml
```

Fails with:

```
2023-12-28T12:14:55.129869Z [main] ERROR /usr/local/cargo/git/checkouts/diem-7dee55d666bb1ba0/db1137b/storage/backup/backup-cli/src/coordinators/restore.rs:79 Restore coordinator failed. {"error":"epoch history restore failed: epoch ending restore failed: Invalid bitvec from the multi-signature"}
Error: epoch history restore failed: epoch ending restore failed: Invalid bitvec from the multi-signature
make: *** [Makefile:220: restore-all] Error 1
```

#### Solution

no solution yet

**Comment by 0o-de-lally** [comment]
New revision of documentation addresses most of these.
